export const INITIAL_TRANSACTIONS = [
  {
    id: "tx-1",
    merchant: "Green Cafe",
    category: "Comida fuera",
    amount: 45.0,
    date: "09:45 AM",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-2",
    merchant: "Transferencia Salario",
    category: "Ingresos",
    amount: 3200.0,
    date: "Ayer",
    account: "Depósito Directo",
    type: "income",
  },
  {
    id: "tx-3",
    merchant: "Netflix Inc",
    category: "Facturas",
    amount: 15.49,
    date: "Hace 2 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-4",
    merchant: "Starbucks Coffee",
    category: "Comida fuera",
    amount: 4.5,
    date: "Hace 3 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-5",
    merchant: "Uber Trip",
    category: "Transporte",
    amount: 18.75,
    date: "Hace 4 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-6",
    merchant: "Supermercado Central",
    category: "Supermercado",
    amount: 142.3,
    date: "Hace 5 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-7",
    merchant: "Tienda de Ropa Z",
    category: "Compras",
    amount: 85.0,
    date: "Hace 10 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-8",
    merchant: "Compañía de Luz",
    category: "Facturas",
    amount: 110.0,
    date: "Hace 15 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-9",
    merchant: "Pizzería Roma",
    category: "Comida fuera",
    amount: 32.5,
    date: "Hace 25 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-10",
    merchant: "Transferencia Salario M-1",
    category: "Ingresos",
    amount: 3200.0,
    date: "Hace 30 días",
    account: "Depósito Directo",
    type: "income",
  },
  {
    id: "tx-11",
    merchant: "Abono Internet",
    category: "Facturas",
    amount: 45.0,
    date: "Hace 40 días",
    account: "Tarjeta de Crédito",
    type: "expense",
  },
  {
    id: "tx-12",
    merchant: "Gasolinera Total",
    category: "Transporte",
    amount: 60.0,
    date: "Hace 60 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-13",
    merchant: "Compra Gadget",
    category: "Compras",
    amount: 199.99,
    date: "Hace 75 días",
    account: "Tarjeta de Crédito",
    type: "expense",
  },
  {
    id: "tx-14",
    merchant: "Transferencia Salario M-2",
    category: "Ingresos",
    amount: 3200.0,
    date: "Hace 60 días",
    account: "Depósito Directo",
    type: "income",
  },
  {
    id: "tx-15",
    merchant: "Supermercado Central XL",
    category: "Supermercado",
    amount: 220.5,
    date: "Hace 90 días",
    account: "Tarjeta Personal",
    type: "expense",
  },
  {
    id: "tx-16",
    merchant: "Seguro de Auto",
    category: "Facturas",
    amount: 150.0,
    date: "Hace 120 días",
    account: "Tarjeta de Crédito",
    type: "expense",
  },
  {
    id: "tx-17",
    merchant: "Mantenimiento Hogar",
    category: "Otros",
    amount: 350.0,
    date: "Hace 150 días",
    account: "Efectivo",
    type: "expense",
  },
];

export const INITIAL_BUDGETS = [
  {
    category: "Comida fuera",
    spent: 49.5, // 4.50 (Starbucks) + 45.00 (Green Cafe)
    limit: 120.0,
    icon: "Utensils",
    color: "#EAB308", // Amber
  },
  {
    category: "Transporte",
    spent: 18.75,
    limit: 150.0,
    icon: "Car",
    color: "#3B82F6", // Blue
  },
  {
    category: "Supermercado",
    spent: 142.3,
    limit: 300.0,
    icon: "ShoppingBag",
    color: "#10B981", // Emerald
  },
  {
    category: "Facturas",
    spent: 15.49,
    limit: 100.0,
    icon: "Receipt",
    color: "#8B5CF6", // Purple
  },
  {
    category: "Compras",
    spent: 85.0,
    limit: 200.0,
    icon: "Tag",
    color: "#EC4899", // Pink
  },
  {
    category: "Otros",
    spent: 0.0,
    limit: 100.0,
    icon: "HelpCircle",
    color: "#6B7280",
  },
];


export const INITIAL_SAVINGS = {
  name: "Fondo de Emergencia",
  target: 5000.0,
  current: 450.0,
};

export const INITIAL_CHAT_HISTORY = [
  {
    id: "chat-1",
    sender: "ai",
    timestamp: "09:41 AM",
    text: "¡Buenos días! He analizado tus transacciones recientes. Actualmente estás S/ 120 por debajo del presupuesto para 'Comida fuera' esta semana. ¿Te gustaría que lo transfiera a tu meta de ahorro?",
    actionChips: [
      { text: "Ver Estadísticas", actionId: "ask_view_limits" },
      { text: "Ignorar", actionId: "ignore" },
    ],
  },
  {
    id: "chat-2",
    sender: "user",
    timestamp: "09:45 AM",
    text: "De hecho, acabo de registrar S/ 45 para el almuerzo en Green Cafe.",
  },
  {
    id: "chat-3",
    sender: "ai",
    timestamp: "09:45 AM",
    text: "Entendido. He registrado ese gasto. Aquí está el detalle de la transacción actualizado:",
    transactionDetail: {
      id: "tx-1",
      merchant: "Green Cafe",
      category: "Comida fuera",
      amount: 45.0,
      date: "09:45 AM",
      account: "Tarjeta Personal",
      type: "expense",
    },
    infoText: "Te quedan S/ 75 en 'Comida fuera' para esta semana.",
  },
  {
    id: "chat-4",
    sender: "user",
    timestamp: "09:47 AM",
    text: "También acabo de recibir un pago de S/ 150 por consultoría. Registra eso por favor.",
  },
  {
    id: "chat-5",
    sender: "ai",
    timestamp: "09:47 AM",
    text: "¡Excelente! He registrado ese ingreso de consultoría en tu historial.",
    transactionDetail: {
      id: "tx-demo-income",
      merchant: "Consultoría Freelance",
      category: "Ingresos",
      amount: 150.0,
      date: "09:47 AM",
      account: "Depósito Directo",
      type: "income",
    },
    infoText: "Tus ingresos totales de esta semana han aumentado a S/ 3.350,00.",
    actionChips: [
      { text: "Ver Estadísticas", actionId: "ask_view_limits" },
    ],
  },
  {
    id: "chat-6",
    sender: "user",
    timestamp: "09:49 AM",
    text: "Creo que gastaré más esta semana en Compras. Sube mi límite de presupuesto de Compras a S/ 300.",
  },
  {
    id: "chat-7",
    sender: "ai",
    timestamp: "09:49 AM",
    text: "He ajustado tu límite semanal para la categoría **Compras** de S/ 200,00 a **S/ 300,00**.",
    infoText: "Presupuesto actualizado: Compras (Límite: S/ 300,00, Gastado: S/ 85,00).",
    actionChips: [
      { text: "Ver presupuestos", actionId: "ask_view_limits" },
    ],
  },
];
